FROM fedora:42

WORKDIR /root

RUN sh -c "$(curl -fsLS get.chezmoi.io)"
RUN mv ./bin/chezmoi /usr/bin/
RUN dnf update -y

# remove later
RUN dnf install ansible neovim zsh flatpak -y

COPY . /root/.local/share/chezmoi

# RUN chezmoi apply

ENTRYPOINT ["chezmoi", "apply"]

