FROM fedora:40

WORKDIR /root

RUN sh -c "$(curl -fsLS get.chezmoi.io)"
RUN mv ./bin/chezmoi /usr/bin/
RUN dnf update -y
RUN dnf install ansible -y

COPY . /root/.local/share/chezmoi

ENTRYPOINT ["tail", "-f", "/dev/null"]

