#!/usr/bin/env bash

alias ll="ls -la"
alias ln="ln -v"
alias mkdir="mkdir -p"
alias mv="mv -v"
alias e="nvim"
alias rm="echo Use the full path '/bin/rm', or use trash/gio trash"
alias cat="bat"

# Pretty print path
alias path='echo $PATH | tr -s ":" "\n"'

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- -="cd -"

alias reload="exec ${SHELL} -l"

alias lzg="lazygit"
alias lzd="lazydocker"

# Include custom aliases
[[ -f ~/.aliases.local ]] && source ~/.aliases.local
