#!/usr/bin/env bash

alias ll="ls -la"
alias ln="ln -v"
alias mkdir="mkdir -p"
alias e="$EDITOR"
alias rm="echo Use the full path '/bin/rm', or use trash/gio trash"

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

alias reload="exec ${SHELL} -l"

alias lzg="lazygit"
alias lzd="lazydocker"

# Include custom aliases
[[ -f ~/.aliases.local ]] && source ~/.aliases.local
